apiVersion: v1
kind: LimitRange
metadata:
  name: blockchain-backend-limit-range
spec:
  limits:
  - default:
      cpu: 500m
      memory: 128Mi
    defaultRequest:
      cpu: 250m
      memory: 64Mi
    type: Container
  - max:
      cpu: 1
      memory: 512Mi
    min:
      cpu: 100m
      memory: 32Mi
    type: Pod
  - max:
      cpu: 2
      memory: 1Gi
    type: Container