#!/bin/bash

# Script to invalidate CloudFront cache for Dapp-2578 distribution
# Usage: ./scripts/invalidate-cloudfront.sh <distribution-id> [paths]
# Example: ./scripts/invalidate-cloudfront.sh E1234567890ABCDEF "/*"

set -e

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "AWS CLI is not installed. Please install it first."
    exit 1
fi

# Check if distribution ID is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <distribution-id> [paths]"
    echo "Example: $0 E1234567890ABCDEF \"/*\""
    echo "For Dapp-2578 distribution, use the actual distribution ID generated by AWS"
    exit 1
fi

DISTRIBUTION_ID=$1
PATHS=${2:-"/*"}

echo "Invalidating Dapp-2578 CloudFront distribution: $DISTRIBUTION_ID"
echo "Paths to invalidate: $PATHS"

# Create invalidation
aws cloudfront create-invalidation \
    --distribution-id "$DISTRIBUTION_ID" \
    --paths "$PATHS" \
    --query 'Invalidation.Id' \
    --output text

echo "Dapp-2578 invalidation request submitted successfully."